# Docker - PostgreSQL config
# Active when SPRING_PROFILES_ACTIVE=docker (set in docker-compose.yml)
spring.datasource.url=jdbc:postgresql://postgres:5432/orderdb
spring.datasource.username=aviraj
spring.datasource.password=aviraj123
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.h2.console.enabled=false
eureka.client.service-url.defaultZone=http://discovery-server:8761/eureka/
